---
title: "Creating count data and descriptives"
author: "Fabian Scheifele"
date: "3 6 2022"
output: html_document
uses: "y2_final95.rds"
creates: "y2_count.rds"

---

1. packages
```{r}
suppressMessages(memory.limit(size = NA))

if(!require(install.load)){
  install.packages("install.load")
  library(install.load)
}
suppressMessages(install_load("tidyverse", "dplyr", "ggplot2", "readr", "readxl","knitr","here", "tidyverse" , "anytime" , "data.table", "corrplot", "naniar", "fuzzyjoin","expss", "janitor","readr", "data.table", "labelled", "countrycode"))

`%notin%` <- Negate(`%in%`)
```

2. import data
```{r}
y2_fam_final<-readRDS(here("data","intermediate","Y02_intl_pat_families_1995.rds"))

#how many distinct IPC codes per firm
y2_fam_final<-y2_fam_final%>%group_by(docdb_family_id)%>%
  mutate(distinct_cpc=n_distinct(cpc), distinct_inv=n_distinct(person_id), distinct_year=n_distinct(earliest_filing_year))

summary(y2_fam_final$distinct_cpc)
summary(y2_fam_final$distinct_inv)
summary(y2_fam_final$distinct_year)

different_years<-y2_fam_final%>%filter(distinct_year>1)
length(unique(different_years$docdb_family_id))
#For 2459 patents the earliest_filing_year is not uniform across different applications of the same family, in those cases the earliest year is taken as family filing year#
y2_fam_final<-y2_fam_final%>%
  group_by(docdb_family_id)%>%
  mutate(earliest_fam_filing_year=min(earliest_filing_year))
  
length(unique(y2_fam_final$earliest_fam_filing_year))/length(unique(y2_fam_final$earliest_fam_filing_year))
#no filing year unique

y2_fam_final<-y2_fam_final%>%arrange(desc(distinct_inv), docdb_family_id)

large_families<-y2_fam_final%>%filter(distinct_inv>40)
length(unique(large_families$docdb_family_id))

length(unique(large_families$docdb_family_id))/length(unique(y2_fam_final$docdb_family_id))

inv_counts<-y2_fam_final%>%distinct(docdb_family_id,distinct_inv)
summary(inv_counts$distinct_inv)
hist(inv_counts$distinct_inv)


```


3. Creating fractional count by appln_id for y2_final (with replaced residences)
```{r}
#Create fractional count (each family-invest-CPC combination is one row with the fraction of this inventor-CPC combination)
y2_fam_final<-y2_fam_final%>%
  group_by(docdb_family_id)%>%
  mutate(frac=1/n())

#test to show that person-cpc combination is indeed one row
test<-y2_fam_final%>%filter(appln_id==488313783)%>%select(docdb_family_id, appln_id, person_id,cpc)%>%
  arrange(person_id,cpc)

#Calculate Patent Counts
pat_count<-y2_fam_final%>%
  group_by(person_ctry_code, earliest_fam_filing_year, cpc)%>%
  summarize(pat_count=sum(frac))

#remove white space in between
pat_count$cpc<-gsub(" ", "", pat_count$cpc, fixed = TRUE)

#Merge CPC descriptions to data#
cpc_test<-read_excel(here("data","raw","cpc_description.xlsx"), col_names = TRUE)
pat_count<-left_join(pat_count, cpc_test, by=c("cpc"="CPC"))

#merge countrycodes to data
#country_codes<-read_excel(here("data","wipo_codes.xlsx"))
library(countrycode)
pat_count$country<-countrycode(pat_count$person_ctry_code, origin = 'iso2c', destination = 'country.name')

nonames<-pat_count%>%
  filter(is.na(country))
#80 observations either relate to outdated country codes or to accidently put patent office codes, 
#observations are dropped as they cannot be attributed to specific country

pat_count<-pat_count%>%filter(!is.na(country))
```

4.Calculate (unrestricted) Revealed Technological advantages
```{r}
pat_count<-pat_count%>%group_by(country,earliest_fam_filing_year)%>%
  mutate(sum_country_year=sum(pat_count))%>%
  ungroup()%>%
  group_by(cpc, earliest_fam_filing_year)%>%
  mutate(sum_cpc_year=sum(pat_count))%>%
  ungroup()%>%
  group_by(earliest_fam_filing_year)%>%mutate(total_pat_year=sum(pat_count))%>%
  ungroup()%>%
  mutate(rta=(pat_count/sum_country_year)/(sum_cpc_year/total_pat_year))
```
5. Some tests on the data
```{r}
pat_count%>%slice_max(rta,n=20)%>%select(country, earliest_fam_filing_year, cpc, rta)
```


