---
title: "master_greenpat_complexity"
author: "Fabian Scheifele"
date: "29 4 2022"
output: html_document
---


```{r}
suppressMessages(memory.limit(size = NA))

if(!require(install.load)){
  install.packages("install.load")
  library(install.load)
}
suppressMessages(install_load("tidyverse", "dplyr", "ggplot2", "readr", "readxl","knitr","here", "tidyverse" , "anytime" , "data.table", "corrplot", "naniar", "fuzzyjoin","expss", "janitor","readr", "data.table", "labelled", "countrycode"))

`%notin%` <- Negate(`%in%`)
```

1. Import data 
```{r}
y2_raw<-read_csv(here("data","Y02_v07_new.csv"), locale=locale(encoding = "latin1"))
#2373038 rows compared to 1521030 in previous dataset means only 1.56 IPC codes per patent application, not a lot?

#Rename some variables
y2_raw<-y2_raw%>%rename(row_no=...1)
y2_raw<-y2_raw%>%rename(application_number=X.2)
y2_raw<-y2_raw%>%rename(cpc=CPC_CLASS_SYMBOL)


countries_unique<-unique(y2_raw$NUTS)
#182 different countries

#inv_country<-fread(here("data","ctry_inv_person.txt"))
```

2. Clean data
```{r}
#make columns lower case
names(y2_raw) <- tolower(names(y2_raw))
#remove spaces in CPC codes for matching with descriptions
y2_raw<-y2_raw%>%mutate(cpc=str_replace(cpc," ",""))

# add labels to remaining variables
y2_raw<- apply_labels(y2_raw,
                      row_no = "Row number as imported",
                      application_number = "applications, numbered as imported",appln_id = "patstat application ID", 
                      appln_auth = "Patent Office",
                      person_id = "patstat person ID",
                      person_name = "Name of the Applicant or Inventor",
                      person_address = "All address elements of the person apart from the country",
                      nuts = "NUTS code as defined by Eurostat",
                      nuts_level = "Indicates the level of the regionalisation code in attribute NUTS, 0=state",
                      doc_std_name_id = "ID for the DOCDB standardised name",
                      doc_std_name = "Standardised name as recorded in DOCDB",
                      psn_id = "ID for the PATSTAT Standardised Name",
                      psn_level="Harmonisation level of PATSTAT standardised name",
                      psn_level=c("No harmisation"=0, "Automated harmonisation"=1, "Automated plus manual refinement"=2),
                      han_id="ID of a Harmonised Applicant Name (HAN) from OECD",
                      han_name="Harmonised Applicant Name (HAN) from OECD",
                      han_harmonized="Harmonisation indicator for OECD HAN",
                      han_harmonized=c("replinished with original name"=0, "harmonized, but not matched with orbis"=1, "harmonized and matched"=2),
                      earliest_publn_year="Year of the earliest publication date of an application", 
                      earliest_filing_year= "Year of earliest application filing",
                      docdb_family_size="family size, 1 means application is only family member", 
                      docdb_family_id ="ID of patent family"
)


#make all string variables to lower case
y2_raw <- y2_raw %>%
  mutate(across(where(is.character), tolower))


#Code factor variables
y2_raw$granted<- ifelse(y2_raw$granted=='y',1,0)

```


3. Seperate raw data into applicant and inventor file
```{r}
#Seperating applicants
applicants<-y2_raw%>%filter(applt_seq_nr==1)
applicants_nocountry<-applicants%>%filter(is.na(nuts))
  #12,58% NA's for applicant residence


#Seperating inventors
inventors<-y2_raw%>%filter(invt_seq_nr>0)%>%
  arrange(docdb_family_id, appln_id)%>%
  select(docdb_family_id,nuts,cpc, earliest_filing_year)
inventors_nocountry<-inventors%>%filter(is.na(nuts))
  #15% NA's for inventor residence

#Testing for number of unique CPC codes
cpc_inventor<-inventors %>%
  group_by(docdb_family_id) %>%
  mutate(unique_cpc = n_distinct(cpc))
summary(cpc_inventor$unique_cpc)

cpc_applicant<-applicants %>%
  group_by(docdb_family_id) %>%
  mutate(unique_cpc = n_distinct(cpc))
summary(cpc_applicant$unique_cpc)
  #Only one CPC code per family_id--> weird

#Testing for number of unique CPC codes
cpc<-y2_raw %>%
  group_by(docdb_family_id) %>%
  mutate(unique_cpcs_family = n_distinct(cpc))%>%
  ungroup()%>%
  group_by(appln_id) %>%
  mutate(unique_cpcs_appln = n_distinct(cpc))%>%
  select(appln_id, docdb_family_id, nuts_new, unique_cpcs_family, unique_cpcs_appln)

cpc%>%filter(unique_cpcs_appln!=unique_cpcs_family)
#there seem to be no differences between the number of unique CPC codes in invidiual applications and the overall family
```

4. Replace residence of inventor, applicant (NUTS) with Methods from de Rassenfosse (2013)
```{r}
#Check out missing data 
missing_country<-y2_raw%>%filter(is.na(nuts))
empty_country<-y2_raw%>%filter(nuts== "")
#17.2% missing country data#

country_complete<-y2_raw%>%filter(!is.na(nuts))

#merging based on person_id (nothing found)
person_id_found<-missing_country%>%inner_join(country_complete, by=c("person_id"))

#merging based on person_id (nothing found)
han_id_found<-missing_country%>%inner_join(country_complete, by=c("han_name"))

#merging based on psn_id (too large to match)
#psn_id_found<-missing_country%>%inner_join(country_complete, by=c("psn_name"))

#Source 4: Use country of residence of the applicant, as indicated in the priority document, to proxy the country of the inventor



#Source 7: Following the method described in De Rassenfosse (2013), we replace Where available,  missing nationality with Patent Office (better would be priority patent office)
y2_raw<-y2_raw%>%mutate(nuts_new=if_else(is.na(nuts), appln_auth, nuts))
replaced<-y2_raw%>%filter(is.na(nuts))%>%select(appln_auth, nuts, nuts_new)

#Remove replaced values, where patent office is regional
`%notin%` <- Negate(`%in%`)
y2_raw<-y2_raw%>%filter(nuts_new %notin% c("ep", "wo", "ap", "em","bx", "ea", "gc", "ib", "oa", "qz", "xn", "xu", "xv"))

#Create dummy for replaced nationality values
y2_raw<-y2_raw%>%mutate(nat_replaced=if_else(nuts_new==nuts,0,1,missing = 1))
replaced<-y2_raw%>%filter(is.na(nuts))%>%select(appln_auth, nuts, nuts_new,nat_replaced)
mean(y2_raw$nat_replaced)
```


```{r}
inv_country2<-inv_country%>%select(appln_id, person_id, patent_office, priority_year,ctry_code)
inv_country2<- apply_labels(inv_country2,
                      appln_id = "PATSTAT Applicant id")
missing_country$appln_id<-as.integer(missing_country$appln_id)
missing_country<-remove_labels(missing_country)
inv_country2$appln_id<-remove_labels(inv_country2$appln_id)
country_found<-missing_country%>%inner_join(inv_country2, by=c("appln_id"))
compare<-country_found%>%select(appln_id, appln_auth,patent_office, earliest_filing_year,priority_year, person_id.x, person_id.y,ctry_code)

test<-country_found%>%inner_join(country_complete, by=c("appln_id"))
test2<-test%>%select(person_id.x,person_id.y, person_id, person_name.x, person_name.y, ctry_code, nuts.x, nuts.y)
```




5. Creating final count datasets
```{r}
#Counting number of inventors and cpc codes per family_id
inventors<-inventors%>%group_by(docdb_family_id)%>%
  mutate(no_inventors=n())
inventors<-inventors%>%group_by(docdb_family_id)%>%
  mutate(no_cpc=n_distinct(cpc))

#creating fractional count variable
inventors<-inventors%>%mutate(frac_count=1/(no_cpc*no_inventors))

#Grouping the data by nationality
inventor_final<-inventors%>%group_by(nuts, cpc, earliest_filing_year)%>%
  summarize(frac_pat_count=sum(frac_count))
inventor_final<-inventor_final%>%arrange(nuts,earliest_filing_year, cpc)

#remove NA's
inventor_final<-inventor_final%>%filter(!is.na(nuts))

#Calculate RCA
inventor_final<-inventor_final%>%
  group_by(nuts, earliest_filing_year)%>%
  mutate(rta_nom=frac_pat_count/sum(frac_pat_count))%>%
  ungroup%>%
  group_by(earliest_filing_year, cpc)%>%
  mutate(rta_denom=frac_pat_count/sum(frac_pat_count))%>%
  ungroup%>%
  mutate(rta=rta_nom/rta_denom)

```


6. Fractional count by appln_id
```{r}
#remove NA's
inventor_final<-y2_raw%>%filter(!is.na(nuts))%>%select(nuts,appln_id,person_id, earliest_filing_year, cpc)

#Create fractional count (each person-CPC combination is one row)
inventor_final<-inventor_final%>%group_by(appln_id)%>%mutate(frac=1/n())

#test to show that person-cpc combination is indeed one row
#test<-inventor_final%>%filter(appln_id==488313783)%>%arrange(person_id)

nationality<-as.data.frame(unique(inventor_final$nuts))


#Calculate Patent Counts
pat_count<-inventor_final%>%
  group_by(nuts, earliest_filing_year, cpc)%>%summarize(pat_count=sum(frac))


pat_count<-pat_count%>%group_by(nuts,earliest_filing_year)%>%mutate(sum_country=sum(pat_count))%>%
  ungroup()%>%
  group_by(cpc, earliest_filing_year)%>%
  mutate(sum_cpc=sum(pat_count))%>%
  ungroup()%>%
  group_by(earliest_filing_year)%>%mutate(sum_year=sum(pat_count))%>%
  ungroup()%>%
  mutate(rta=(pat_count/sum_country)/(sum_cpc/sum_year))

#Merge CPC descriptions to data#
cpc_test<-read_excel(here("data","cpc_description.xlsx"), col_names = TRUE)
cpc_test$CPC<-str_squish(cpc_test$CPC)
names(cpc_test) <- tolower(names(cpc_test))
cpc_test <- cpc_test %>%
  mutate(across(where(is.character), tolower))

pat_count<-left_join(pat_count, cpc_test, by=c("cpc"="cpc"))

#merge countrycodes to data
country_codes<-read_excel(here("data","wipo_codes.xlsx"))
country_codes$nuts <-tolower(country_codes$nuts)
pat_count$nuts<-as.character(pat_count$nuts)
pat_count<-left_join(pat_count,country_codes, by=c("nuts"))
```

Descriptive Statistics on the data
```{r}
#top_cpc codes
top_cpc<-pat_count%>%group_by(cpc)%>%
  summarize(count=sum(pat_count))
top_cpc<-left_join(x=top_cpc, y=cpc_test, by="cpc")%>%arrange(desc(count))

#main countries
top_countries<-pat_count%>%group_by(nuts)%>%
  summarize(count=sum(pat_count))%>%arrange(desc(count))
top_countries<-left_join(top_countries,country_codes, by=c("nuts"))

#12 country country codes not present in https://www.uspto.gov/patents/apply/applying-online/country-codes-wipo-st3-table#heading-2
no_countryname<-top_countries%>%filter(is.na(country))
```

Alternative read in of data with fread
```{r}
y2_raw_fread<-fread(here("data","Y02_v07_new.csv"), header = T, sep = ",",na.strings = c("",NA),data.table=F, stringsAsFactors = FALSE, fill = FALSE, strip.white = TRUE)

countries_fread<-as.data.frame(unique(y2_raw_fread$NUTS))

#remove NA's
inventor_final2<-y2_raw_fread%>%filter(!is.na(nuts))%>%select(nuts,appln_id,person_id, earliest_filing_year, cpc)

#Create fractional count (each person-CPC combination is one row)
inventor_final2<-inventor_final2%>%group_by(appln_id)%>%mutate(frac=1/n())

#test to show that person-cpc combination is indeed one row
#test<-inventor_final%>%filter(appln_id==488313783)%>%arrange(person_id)

nationality<-as.data.frame(unique(inventor_final2$nuts))


#Calculate Patent Counts
pat_count<-inventor_final2%>%
  group_by(nuts, earliest_filing_year, cpc)%>%summarize(pat_count=sum(frac))


pat_count<-pat_count%>%group_by(nuts,earliest_filing_year)%>%mutate(sum_country=sum(pat_count))%>%
  ungroup()%>%
  group_by(cpc, earliest_filing_year)%>%
  mutate(sum_cpc=sum(pat_count))%>%
  ungroup()%>%
  group_by(earliest_filing_year)%>%mutate(sum_year=sum(pat_count))%>%
  ungroup()%>%
  mutate(rta=(pat_count/sum_country)/(sum_cpc/sum_year))
```

